### PR TITLE
fix: webhook panics due to logging

### LINKED ISSUE #2217: [BUG] `addPrometheusConfig` in the mutating webhook always panics
## Description
Every time the pod webhook runs it causes a panic in the mutating webhook logs. 

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Reproduction Code [Required]
I'm pretty sure running any `SparkApplication` will reproduce. 

Create a `SparkApplication` then look at the webhook logs

## Expected behavior
All the expected mutations happen and no errors are logged. 

## Actual behavior
Logs
```
2024-10-03T18:11:01.950Z	INFO	webhook/sparkpod_defaulter.go:339	could not mount volume %s in path %s	{"delegated-gen2-enrichment-targetless-vehic-863635-prom-conf-vol": "/etc/metrics/conf"}
2024-10-03T18:11:01.950Z	DPANIC	webhook/sparkpod_defaulter.go:341	odd number of arguments passed as key-value pairs for logging	{"ignored key": 1099}
github.com/kubeflow/spark-operator/internal/webhook.addPrometheusConfig
	/workspace/internal/webhook/sparkpod_defaulter.go:341
github.com/kubeflow/spark-operator/internal/webhook.mutateSparkPod
	/workspace/internal/webhook/sparkpod_defaulter.go:136
github.com/kubeflow/spark-operator/internal/webhook.(*SparkPodDefaulter).Default
	/workspace/internal/webhook/sparkpod_defaulter.go:92
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*defaulterForType).Handle
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.5/pkg/webhook/admission/defaulter_custom.go:80
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.5/pkg/webhook/admission/webhook.go:169
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.5/pkg/webhook/admission/http.go:119
sigs.k8s.io/controller-runtime/pkg/webhook/internal/metrics.InstrumentedHook.InstrumentHandlerInFlight.func1
	/go/pkg/mod/github.com/prometheus/client_golang@v1.19.1/prometheus/promhttp/instrument_server.go:60
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2220
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1
	/go/pkg/mod/github.com/prometheus/client_golang@v1.19.1/prometheus/promhttp/instrument_server.go:147
net/http.HandlerFunc.ServeHTTP
```

I think the important part is `webhook/sparkpod_defaulter.go:341	odd number of arguments passed as key-value pairs for logging	{"ignored key": 1099}`. 

In addition to logging an error I suspect [these mutations](https://github.com/kubeflow/spark-operator/blob/94cdc526d93a8501aadfbde729c9ff906ce599cf/internal/webhook/sparkpod_defaulter.go#L127-L132) are not happening. Finally, I'm pretty sure its logging "could not" after succeeding, so that is a bit confusing. 

## Environment & Versions

- Spark Operator App version: 2.0.1
- Helm Chart Version: 2.0.1
- Kubernetes Version: 1.29.7
- Apache Spark version: 3.5.0

### PR DESCRIPTION
**Pull request by ChenYi015**
## Purpose of this PR

Close #2217

## Change Category
Indicate the type of change by marking the applicable boxes:

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that could affect existing functionality)
- [ ] Documentation update

## Checklist
Before submitting your PR, please review the following:

- [x] I have conducted a self-review of my own code.
- [ ] I have updated documentation accordingly.
- [ ] I have added tests that prove my changes are effective or that my feature works.
- [x] Existing unit tests pass locally with my changes.

### CODE REVIEW

File: internal/webhook/sparkpod_defaulter.go [hunk 1]
```diff
@@ -191,7 +191,7 @@ func addVolume(pod *corev1.Pod, volume corev1.Volume) error {
 func addVolumeMount(pod *corev1.Pod, mount corev1.VolumeMount) error {
 	i := findContainer(pod)
 	if i < 0 {
-		logger.Info("not able to add VolumeMount %s as Spark container was not found in pod %s", mount.Name, pod.Name)
+		return fmt.Errorf("failed to add volumeMounts as Spark container not found")
 	}
```
Comment (ImpSy) [inline internal/webhook/sparkpod_defaulter.go:195]: why not modify findContainer to return a tuple (int, error) instead ?
And call it earlier in the code instead of every patch  operation

Comment (ChenYi015) [reply internal/webhook/sparkpod_defaulter.go:195]: Yes, the logic of findContainer can be optimized as you said, maybe we can do it in a separated PR.

**Comment by ChenYi015** [comment]
@ImpSy Thanks for your review. I can see that you have been contributing to spark operator a lot in recent months.  Would you like to be a reviewer of spark operator? We can make you a reviewer by adding you to the [OWNERS](https://github.com/kubeflow/spark-operator/blob/master/OWNERS) file if you would like.

**Comment by ImpSy** [comment]
Yes I would love to, do I need to create a PR to join the kubeflow org first ?

**Comment by ChenYi015** [comment]
> Yes I would love to, do I need to create a PR to join the kubeflow org first ?

Yes, please follow this [guide](https://www.kubeflow.org/docs/about/membership/#member) to be a member of kubeflow.

**Comment by ImpSy** [comment]
Ok thanks will do thanks 🙏 
I question: Who would be my 2nd sponsor ?

**Comment by ChenYi015** [comment]
@ImpSy Cloud you reach me out in Slack?

**Comment by ImpSy** [comment]
Sorry it's still early here I'll do it as soon as I can

**Review by ImpSy — APPROVED** [review]
